### ISSUE TITLE
Option for choosing a control group

### ISSUE THREAD

**Issue by yujunghwang** [chaisemartinPackages/did_multiplegt_dyn#24]
Question: is there an option for did_multiplegt_dyn to use only never treated as control, like Callaway and Sant'Anna or Sun and Abraham ?? I looked up the help file and my understanding is no. Am I correct? Thx for preparing these awesome packages !

**Comment by chaisemartinPackages** [comment]
Hi Yujung,
Thanks for your interest in did_multiplegt_dyn!
We have just introduced a new option ("only_never_switchers") to perform switchers vs never_switchers comparisons.
You can check it out by simply updating your version of the package:

Stata: ssc install did_multiplegt_dyn, replace
R: install.packages("DIDmultiplegtDYN", force = TRUE)

Best,
Diego

**Comment by yujunghwang** [comment]
This is amazing! Thank you for adding this option for many researchers.

Best,
Yujung
