### ISSUE TITLE
Discrepency in names for stored elements after estimation

### ISSUE THREAD

**Issue by Vincent-Nossek** [chaisemartinPackages/did_multiplegt_dyn#37]
Dear authors,
after trying to use the saved results (i.e. like e(X)) from did_multiplegt_dyn I noticed that the names given in the "help" file (after calling help did_multiplegt_dyn) did not work. 
After calling "ereturn list" I noticed that most of the results are stored under different names than the one given in the help file.
For instance help file gives "e(effect_average)" while the true name is "e(Av_tot_effect)".
Under the scalars stored results most names are different except for the standard errors.
Under the Macro and Matrix it looks like the names are the same.

PS: I'm guessing it would be simpler to correct the help file, but having the same names for the saved results between did_multpiplegt_dyn and former did_multiplegt might make it easier for people when switching between both command.

Best regards,
Vincent

**Comment by chaisemartinPackages** [comment]
Dear Vincent,
This is Diego from Clément de Chaisemartin's RA Team.
Thanks for your interest in did_multiplegt_dyn!
It seems that you may be using an older version of did_multiplegt_dyn. I checked running the program with a random DGP and the names of the ereturn seem consistent with the help file:
![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/125619230/1600471e-4b54-49c5-a001-242ec438d6fd)

![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/125619230/451b4368-1bf4-4558-a9ce-7f76bf2ed9b4)

Try updating the program with:
```stata
ssc install did_multiplegt_dyn, replace
```
and let me know if this solves the issue.
Best,
Diego

**Comment by Vincent-Nossek** [comment]
Dear Diego, 
thanks for the prompt response!
Indeed updating the package seems to have resolved the issue, the help document have the new names matching with ereturn list. 
Best,
Vincent
