### ISSUE TITLE
Comparability of placebo and effects in ES plots in the R version

### ISSUE THREAD

**Issue by mmeleseg** [chaisemartinPackages/did_multiplegt_dyn#52]
First of all, thank you so much for creating and sharing this wonderful tool. 

I am writing to ask regarding the comparability of the placebo and post-treatment coefficients for an event study analysis using the R version of did_multiplegt_dyn (as noted in Jonathan Roth's paper). Does the default setting in R still has this issue (asymmetric construction of placebo and effects)? If so, what would researchers need to do in order to generate comparable placebo and effects estimates (such as using the "long differences" for both) when using the R version of did_multiplegt_dyn?

**Comment by chaisemartinPackages** [comment]
Dear Mesay,
This is Diego from Clement de Chaisemartin's RA Team.
Thanks for your interest in DIDmultiplegtDYN!
The paper by Jonathan Roth used the DIDmultiplegt R package, which is now no longer actively updated. Differently from the old package, DIDmultiplegtDYN, i.e. the R version of did_multiplegt_dyn that is currently maintained, implements by default long differences in the computation of both placebos and dynamic effects. As a result, DIDmultiplegtDYN does not suffer anymore from an asymmetric construction of placebo and effects.
I hope this helps!
Best,
Diego

**Comment by mmeleseg** [comment]
Dear Diego, 

Thank you so much for your prompt response. I am glad to hear that the asymmetry is no longer an issue. 

Is the new extension to generate all placebos, "did_multiplegt_dyn_all_pl", also available in the R version?

Thanks!
Mesay

**Comment by chaisemartinPackages** [comment]
Dear Mesay,
Unfortunately, for the moment it is only available on Stata. 
However, given the interest of users for this subcommand, I can expect this routine to be also available for Stata users soon.
We will keep you updated.
Best,
Diego

**Comment by mmeleseg** [comment]
Sound good. 

Thanks for the response, Diego. I appreciate all the work you and the team has done to produce and maintain this package.
