### ISSUE TITLE
SE inconsistency in did_multiplegt_dyn STATA

### ISSUE THREAD

**Issue by fcabrerahz** [chaisemartinPackages/did_multiplegt_dyn#53]
Hello all,

In august 2023 I used the did_multiplegt_dyn command in Stata to evaluate an unconditional scholarship for individuals in primary schools in Mexico. Recently, one government official tried to replicate my results with an updated version of the did_multiplegt_dyn command, and now the standard errors are very different, now are very big (see images below). 

The setup is the next one: from 2018 to 2023, I have schools treated with a scholarship at the student level and others non-treated. I used continuous and binary definitions of the treatment. I have a staggered implementation. In the binary treatment, the one I show below, my definition is “once treated, always treated”, then we do not have schools switching in and out, only switching in.

I have read a 2022 version of the paper about intertemporal treatment effects and the most recent version from January 2014. I cannot see differences in the section “inference”. 

This image shows my “original” estimations of the effect of the scholarship on dropout rates at the school level:

 
![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/95443429/0b5d4021-cd0f-42ff-bdd3-999b56fe9ee3)

I have some problems of pretrends, but that is not my concern. My real problem now is that with the exact same data and specifications ---but with a newer version of the command in STATA, I get this: 

 
![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/95443429/e911f5e3-e40c-4c44-9688-cde6df6aa7fa)

Furthermore, replicating this with the newest version of the command in R, I get something more similar to what I used to obtain with the “old” did_multiplegt_dyn. For example: 

 
![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/95443429/25a4a5dc-e496-4eca-a690-3b35078a230c)

My specification in Stata is this: 

did_multiplegt_dyn abandonoi school_id year treat_med, ///
effects(3) placebo(2) effects_equal controls($controls) trends_nonparam(pan_marg) /// 
weight(alumni) cluster(munid) ///

Taking out the non_parametric trends does not change much the story. Also including the less_conservative_se option does not change the situation. What does change my SE, and actually make them more similar to my previous ones, is getting rid of the cluster option (I cluster at the municipality level).

I would really appreciate any help or information on updates on how the standard errors are now computed in STATA. Many thanks in advance. 

Best,

Dr. Francisco Cabrera
CIDE, Mexico City.

**Comment by fcabrerahz** [comment]
I have now seen that it is the clustered SE computation that causes the divergence. I can more or less replicate my old and the R-software standard errors if I use the cluster() option at the group level and not at the municipality. What specifically changed in the Stata command when clustering SE?

**Comment by chaisemartinPackages** [comment]
Dear Francisco,

I have not understood if you finally managed to find a definitive solution or if the 2 packages (R & Stata) still give you different results (this should not happen...). 
Regarding the modifications, we have fixed many bugs and expanded functionalities significantly during the last year, so it is hard to tell you really what happened at which time. 
If you still have a specific issue don't hesitate to write us at chaisemartin.packages@gmail.com.

Best,
Romain

**Comment by fcabrerahz** [comment]
Dear Romain, 

I thank you for your technical support. Indeed, now the two packages give the same (larger) SEs. 

The report by the National Council on the Evaluation of Social Policies (CONEVAL) in Mexico has now been released. This is the federal institution in charge of the impact evaluation of the largest Mexican public policies. Here is the report in Spanish:

 

https://www.coneval.org.mx/EvaluacionDS/PP/CEIPP/Documents/EVALUACIONES/Evaluacion_impacto_BBBJ/Evaluacion_de_impacto_BBBJ.pdf

 

I warned them about SEs miscalculation on the first version of the results, but they continued to publish the report. 

 

I no longer appear as the author of the report and I am only mentioned as a “coordinator”, whatever that means. In the end this is good because I do not endorse their published results.

They clearly wanted to have significant results, and that would not have been the case using the “correct” SEs. Also, in their interpretation many times they ignored the evidence on pre-trends. Afterwards, they spent days on the media talking about “the positive” effects of this scholarship.

I am now preparing the paper with the correct SEs and interpretation for publication at a journal. I would really appreciate if you could give me some light on what the main difference with the computation was, in R and Stata, around the time I contacted you. For example,  It would be very helpful if you could tell me, what was change that you made in R to have the same SEs as in STATA after I contacted you. I do not need to know the code details, but the intuition on the implementation. 

 

This is because my results for the working paper are now going to be different to those ”I obtained” for the government, and this could cause some controversy. I want to make sure that I can explain what the source of the difference on the SEs was.   

 

I really appreciate your help, 

 

Best,

Francisco Cabrera

 

 

De: Clément de Chaisemartin - ERC Repository ***@***.***> 
Enviado el: martes, 17 de septiembre de 2024 09:59 a. m.
Para: chaisemartinPackages/did_multiplegt_dyn ***@***.***>
CC: Francisco Cabrera ***@***.***>; Author ***@***.***>
Asunto: Re: [chaisemartinPackages/did_multiplegt_dyn] SE inconsistency in did_multiplegt_dyn STATA (Issue #53)

 

Dear Francisco,

I have not understood if you finally managed to find a definitive solution or if the 2 packages (R & Stata) still give you different results (this should not happen...).
Regarding the modifications, we have fixed many bugs and expanded functionalities significantly during the last year, so it is hard to tell you really what happened at which time.
If you still have a specific issue don't hesitate to write us at ***@***.*** ***@***.***> .

Best,
Romain
