### ISSUE TITLE
did_multiplegt_dyn with doubly robust estimator

### ISSUE THREAD

**Issue by dilluhn** [chaisemartinPackages/did_multiplegt_dyn#59]
Dear de Chaisemartin's RA Team, 

Thank you for your exciting work on DID estimators!

I was wondering if there is a possibility to combine did_multiplegt_dyn with a doubly robust estimator (or perhaps something similar such as psm or ipw). Do you know if this is possible, and if so, how I would be able to apply this?

Kind regards,
Dylan

**Comment by lbiagini75** [comment]
Can you create a double robust estimator to manually insert in the did_multiplegt_dyn estimator? I believe this is the best solution as it can address selection bias using your specific data.

**Comment by dilluhn** [comment]
Apologies for the late reply. I see you are doing something similar (https://github.com/chaisemartinPackages/did_multiplegt_dyn/issues/66). Do I understand correctly that did_multiplegt_dyn works for you now in conjunction with weights derived from Inverse Propensity Weight? In that case, that might be easiest way for me to go forward. 

If possible, it would be even better if you could give an example of how to create a double robust estimator to manually insert in the did_multiplegt_dyn estimator.

**Comment by chaisemartinPackages** [comment]
Dear Dylan,

Doubly robust estimation is something we did not consider in the did_multiplegt_dyn package yet so I unfortunately can not provide you with a tutorial on how to implement that. As you already mentioned, the weight option allows you to include weights you derived from Inverse Propensity Weighting. For now, we would further suggest you stick with the options provided in did_multiplegt_dyn (like controls, trends_nonparam, etc...) in case you have doubts about the parallel trends assumption being violated (that's probably why you would want to implement a doubly robust procedure?) in your Design.

Best,
Felix

**Comment by dilluhn** [comment]
Dear Felix, 

Thank you for your commment. That is indeed why I'm interested in implementing a doubly robust procedure. For now, I will see if I can tackle the issue using the options provided. 

Best,
Dylan
