### ISSUE TITLE
 did_multiplegt_dyn with repeated cross sectional data

### ISSUE THREAD

**Issue by Ileon99** [chaisemartinPackages/did_multiplegt_dyn#60]
Dear all,
 
I was wondering if we can use the did_multiplegt_dyn package with repeated cross sectional data. 

I did not find information about this, can you help me? 

Thank you in advance for your time.
 
Best regards,
 
Ignacio

**Comment by chaisemartinPackages** [comment]
Dear Ignacio,

First of all sorry for the late reply. Indeed you can use did_multiplegt_dyn with repeated cross-sectional data, for reference you can see the beginning of section 2 of [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3731856), I hope this is what you were looking for.

Best regards,
Felix
