### ISSUE TITLE
Design option and weight [SOLVED]

### ISSUE THREAD

**Issue by lbiagini75** [chaisemartinPackages/did_multiplegt_dyn#66]
Dear Clément de Chaisemartin's Research Team,
I am writing to seek your guidance regarding an issue I've encountered while using the did_multiplegt_dyn function. I attempted to use design 2 (specified as design = list(2,"console")) in conjunction with weights derived from Inverse Propensity Weight. However, this resulted in the following error:
```
Error in `$<-`:
! Assigned data `(df$g_weight_XX * df$N_XX)/sum(df$g_weight_XX, na.rm = TRUE)` must be compatible with existing data.
✖ Existing data has 76 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 0 to size 76.

Backtrace:
    ▆
 1. └─DIDmultiplegtDYN::did_multiplegt_dyn(...)
 2.   ├─base::append(...)
 3.   └─DIDmultiplegtDYN:::did_multiplegt_dyn_design(...)
 4.     ├─base::suppressWarnings(...)
 5.     │ └─base::withCallingHandlers(...)
 6.     ├─base::`$<-`(`*tmp*`, "N_w_XX", value = `<dbl>`)
 7.     └─tibble:::`$<-.tbl_df`(`*tmp*`, "N_w_XX", value = `<dbl>`)
 8.       └─tibble:::tbl_subassign(...)
 9.         └─tibble:::vectbl_recycle_rhs_rows(value, fast_nrow(xo), i_arg = NULL, value_arg, call)

```
This error seems to be generated by row 77 in the subroutine [did_multiplegt_dyn_design](https://github.com/chaisemartinPackages/did_multiplegt_dyn/blob/main/R/R/did_multiplegt_dyn_design.R)

This leads me to question whether design 2 is compatible with the weights option. If it is indeed compatible, could you please advise on how to properly format the weights for use with the weights option?
I have already attempted to set all weight values to 1, but this resulted in the same error. Any insights or suggestions you could provide would be greatly appreciated.
Thank you for your time and assistance.

**Comment by lbiagini75** [comment]
Hi de Chaisermatin RA staff,
to facilitate the solution, I have attached the code and a subset of the database to an email. 
I remain available for any further clarification or information you might need.
Thank you once again for your support.
Best regards,

**Comment by lbiagini75** [comment]
I find the error 
in the line 50 of  [did_multiplegt_dyn_design](https://github.com/chaisemartinPackages/did_multiplegt_dyn/blob/main/R/R/did_multiplegt_dyn_design.R)it is necessary to it necessary to substitute 
mutate(g_weight = sum(.data$weight), na.rm = TRUE) 
with

```
	## Aggregate weights by group
  if (!is.null(weight)) {
    df <- df %>% group_by(.data$group_XX) %>%
      ################
        mutate(g_weight_XX = sum(.data$weight_XX), na.rm = TRUE) 
    ###############
  } else {
    df$g_weight_XX <- 1
  }
  df <- df %>% dplyr::select(-.data$weight_XX)
```

**Comment by chaisemartinPackages** [comment]
Dear Luigi,
This is Diego from Clement de Chaisemartin's RA Team.
Thanks a lot for spotting the bug! I checked myself and the fix works.
Your patch is already up to Github.
Thanks again!
Best,
Diego
