### ISSUE TITLE
Allowing for Flexible Trends By Group/Using the "trends_nonparm" options

### ISSUE THREAD

**Issue by mmeleseg** [chaisemartinPackages/did_multiplegt_dyn#68]
Hello,

I am using county-by-year unbalanced panel data to estimate the effect of a given treatment, and I would like to include flexible differential trends by state. I understand the "trends_nonparm" option allows for that. However, I keep encountering the following problem (which also arises when I try to include additional controls in the "controls" option. 

I am essentially running the following command: 

did_multiplegt_dyn(df= countyXyeardata, outcome="depvar", group="county_id", time="year", treatment = "treated",
                     effects = 9,placebo = 4, trends_nonparam = "state_id", cluster="state_id") 

and I get the following error message (related to "vectbl_recycle_rhs_rows") 

Error in `[[<-`:
! Assigned data `... * df$first_obs_by_gp_XX` must be compatible with existing data.
✖ Existing data has 6957 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 0 to size 6957.

Would you be able to help me figure out if this issue is on my end/I am not using the specifications correctly?

Thanks so much for your help! 
Mesay

**Comment by lbiagini75** [comment]
Dear Mesay, I have inquired about a similar issue in "[by and by_path setting #64](https://github.com/chaisemartinPackages/did_multiplegt_dyn/issues/64)". Can Diego's solution help you resolve the problem?

**Comment by mmeleseg** [comment]
Hi Diego, 
I have emailed you a code snippet and dataset used along with the explanation for the issues I have encountered. I suspect the issue may have to do with how missing values are treated. 

I look forward to hearing from you. Thanks for all your work on this!
Mesay

**Comment by mmeleseg** [comment]
Hi Diego, 
Thanks for fixing the bug. It is working for me now. 
Mesay
