### ISSUE TITLE
did_multiplegt_dyn compatibility with honestdid

### ISSUE THREAD

**Issue by blanelewis** [chaisemartinPackages/did_multiplegt_dyn#77]
Hello. 

I am trying to make honestdid work with did_multiplegt_dyn. I was able to make it work with the earlier version of the estimator--did_multiplegt using code like this:

honestdid, pre(4/5) post(1) vcov(didmgt_vcov) b(didmgt_results_no_avg) mvec(0.0(0.1)1) delta(rm)  coefplot `plotopts'

It seems that the vcov and b names are different under the new version of the estimator. Can you please tell me what the new names are? Or maybe there is a more general problem constraining the use of honestdid with did_multiplegt_dyn. If so, can you please let me know?

Thank you.

**Comment by chaisemartinPackages** [comment]
This issue was present in the older versions of did_multiplegt_dyn, it can just be resolved by updating the package directly in Stata (ssc install did_multiplegt_dyn, replace) or downloading the latest version here from GitHub.
