### ISSUE TITLE
Test of joint nullity of the effects and Test of equality of the effects: what is the difference?

### ISSUE THREAD

**Issue by LuigiBiagini** [chaisemartinPackages/did_multiplegt_dyn#83]
Sorry for this stupid question but I don't understand the difference between the "Test of joint nullity of the effects" and "Test of equality of the effects"?

**Comment by chaisemartinPackages** [comment]
Dear Luigi,

The first one (T1) tests whether all estimated effects are jointly 0. H_01 is : ß_l == 0 for all l >0
The second (T2) tests whether all estimated effects are equal. H_02 is : ß_l == ß_k for all 0 < l,k <= max effect

They test for 2 different situations. T1 allows to identify if you treatment has any detectable (statistically significant) effect. T2 allows to detect a static treatment effect (whether the effect is not dynamic).
What might be misguiding is that H_01 (all effects are nil) implies H_02. However, when you have no effect at all, it seems a bit silly to test whether those effects are time-varying..

Hope this helps,
Romain

**Comment by lbiagini75** [comment]
Thank you for your kind and very precise response.  I  have read the dCDH2024 paper but I need to have other clarifications to allow aligning the R output with the paper. This response allows me to overcome my doubts.
