### ISSUE TITLE
Placebos and CIs

### ISSUE THREAD

**Issue by evecianap** [chaisemartinPackages/did_multiplegt_dyn#84]
Hi,

My results show no confidence intervals for the placebos.

Here is the code and the results for the effect of PB on health facilities from 2005 to 2016: 

> healthf_dcdh1 <- did_multiplegt_dyn(
+   fullsample2,
+   "healthf",
+   "Munic_Id",
+   "year",
+   "MunicOP_OP",
+   effects = 5,                  # no. of post-treatment periods
+   placebo = 3,                   # no. of pre-treatment periods
+   cluster = "municipality"
+ )
> summary(healthf_dcdh1)

**Estimation of treatment effects: Event-study effects**

Estimate SE       LB CI    UB CI    N   Switchers
Effect_1     39.51578 13.99985 12.07657 66.95499 674 40       
Effect_2     39.51578 13.99985 12.07657 66.95499 674 40       
Effect_3     39.51578 13.99985 12.07657 66.95499 674 40       
Effect_4     39.51578 13.99985 12.07657 66.95499 674 40       
Effect_5     45.34026 17.62646 10.79303 79.88750 339 28       

**Average cumulative (total) effect per treatment unit**
Estimate        SE     LB CI     UB CI         N Switchers 
 45.19079  14.84069  16.10358  74.27800     2,724       188 
Average number of time periods over which a treatment effect is accumulated: 3.0952

 

**Testing the parallel trends and no anticipation assumptions**
             Estimate SE LB CI UB CI N   Switchers
Placebo_1    0        0  0     0     674 40       
Placebo_2    0        0  0     0     674 40       
Placebo_3    0        0  0     0     674 40       

Test of joint nullity of the placebos : p-value = 1.0000

**Is there an error with the placebos or it is possible that the estimate is truly 0 with no confidence intervals? What could be the source of this error?**

Best,
Eduardo

**Comment by lbiagini75** [comment]
Hi Eduardo,
IMO, there is a problem with a control variable.  Have you tried to used other variables?

**Comment by evecianap** [comment]
In this specific analysis no control variables were introduced. I have also tried adding different control variables but the results for the placebos do not change.
