### ISSUE TITLE
Change the event period using did_multiplegt_dyn

### ISSUE THREAD

**Issue by xbrown1992** [chaisemartinPackages/did_multiplegt_dyn#87]
Hi
Many thanks for the package and the recent updates!
I am currently using the model for a staggered DID design. Can I change the event period for this package? I know the code "effect(#)" automatically gives event study estimations with event plots, but I want to combine a few periods as one event. For example, leads 1, 2, and 3 combined to form lead 1 as an event. Lag 1,2 ,3 combine to form lag 1 as an entire event. Can I do that by using this package in STATA? Thank you so much!

**Comment by xbrown1992** [comment]
Also, I have another question about control variables. I have two-factor variables with different categories (e.g., education). What should I do with these factor variables if I really want to include them as controls?

**Comment by chaisemartinPackages** [comment]
Hi,

There is no way to do that internally with the command. However, you could aggregate those effects manually by weighting each effect by the number of observations used (as displayed in the table). Keep in mind that those are dynamic effects so aggregating them this way will not necessarily be very consistent with the model. 

One other thing you can do is estimate only 3 effects and use as your aggregated effect the ATT displayed at the bottom of the table. 

Yet an other thing could be to aggregate your periods two-by-two before the estimation and therefore obtain point estimates that are "linear" in time yet closer to the "event"-effect you want to obtain.

Regarding your second question, I will answer in the other Issue you raised.

Best,
Romain
