### ISSUE TITLE
Cluster-specific linear trend

### ISSUE THREAD

**Issue by FBrunamonti** [chaisemartinPackages/did_multiplegt_dyn#96]
Dear all,
Thank you for having worked on this fantastic package. I am heavily using did_multiplegt_dyn to estimate the effect of a continuous treatment. My data is at the county level, but I would like to specify State-specific linear trends. It seems that the trends_lin parameter only allows for county-specific linear trends. Is it possible to specify the linear trend at the level of the cluster, instead of the group? Or is it simpler to define the trends myself and include them as covariates?

**Comment by chaisemartinPackages** [comment]
Hi,
Unfortunately, we do not allow for linear trends at a higher level than unit. You need to code them by yourself and add each state-trend variable in the _controls_() option.
Best, Romain
